// 100 questions du QCM Psychotechnique - Ambassadeur Marketplace
// answer: index of the correct choice (0=A, 1=B, 2=C, 3=D)
// antiFraud: true if question is flagged [ANTI-FRAUDE]

export type Question = {
  q: string;
  choices: [string, string, string, string];
  answer: number;
  antiFraud?: boolean;
};

export const QUESTIONS: Question[] = [
  { q: "Votre priorité face à un commerçant méfiant est de :", choices: ["Forcer la décision", "Comprendre son besoin", "Parler uniquement de commission", "Quitter rapidement"], answer: 1 },
  { q: "Un artisan n'a jamais vendu en ligne. Vous devez d'abord :", choices: ["Lui promettre beaucoup de ventes", "Lui expliquer simplement l'intérêt", "Lui demander de payer immédiatement", "Le comparer à ses concurrents"], answer: 1 },
  { q: "Le meilleur profil vendeur à recruter est :", choices: ["Celui qui a beaucoup de stock invendable", "Celui qui a un bon produit et veut vendre plus", "Celui qui accepte tout sans comprendre", "Celui qui veut seulement tester sans effort"], answer: 1 },
  { q: "Dans votre ville, où chercheriez-vous 3 vendeurs en premier ?", choices: ["Marché, boutiques, réseaux sociaux locaux", "Ministère, banque, hôpital", "Cinéma, plage, stade", "Je ne sais pas"], answer: 0, antiFraud: true },
  { q: "Si un vendeur vous dit « je n'ai pas le temps », vous répondez :", choices: ["Tant pis", "Justement, notre solution peut vous aider à vendre sans tout gérer seul", "Vous devez trouver le temps", "Ce n'est pas mon problème"], answer: 1 },
  { q: "Un bon ambassadeur doit surtout être :", choices: ["Patient, actif et persévérant", "Timide et passif", "Autoritaire", "Indifférent"], answer: 0 },
  { q: "Le rôle principal de l'ambassadeur est de :", choices: ["Faire la comptabilité", "Identifier et recruter des vendeurs", "Livrer les colis", "Fixer tous les prix"], answer: 1 },
  { q: "« De l'aiguille à l'avion » signifie :", choices: ["La marketplace accepte uniquement les avions", "La marketplace est ouverte à presque tous les secteurs", "On vend seulement des outils", "C'est une phrase sans sens"], answer: 1, antiFraud: true },
  { q: "Une commission sur vente signifie :", choices: ["Être payé même sans résultat", "Être payé selon les ventes générées", "Être payé avant de travailler", "Être payé uniquement en cadeaux"], answer: 1 },
  { q: "Face à un refus, la meilleure attitude est :", choices: ["Insister agressivement", "Comprendre l'objection et relancer plus tard", "Supprimer le contact", "Se décourager"], answer: 1 },
  { q: "Un vendeur veut liquider un stock. Vous pensez à :", choices: ["Marketplace", "Assurance", "Médecine", "Transport uniquement"], answer: 0 },
  { q: "Un artisan tunisien de qualité est intéressant parce qu'il :", choices: ["Peut avoir besoin de visibilité", "Ne doit jamais vendre en ligne", "N'a aucune valeur commerciale", "Vend uniquement à l'étranger"], answer: 0 },
  { q: "Quel canal est le plus rapide pour trouver des petits vendeurs ?", choices: ["Groupes Facebook locaux", "Journal officiel", "Archives municipales", "Bibliothèque universitaire"], answer: 0, antiFraud: true },
  { q: "Le meilleur suivi après recrutement consiste à :", choices: ["Disparaître", "S'assurer que le vendeur publie ses produits et progresse", "Lui demander de vendre seul", "Changer de numéro"], answer: 1 },
  { q: "Un bon candidat doit comprendre que ses revenus dépendent :", choices: ["Du hasard uniquement", "De l'activité des vendeurs recrutés", "De son diplôme", "Du nombre d'heures au bureau"], answer: 1 },
  { q: "Si un vendeur demande « combien je vais vendre ? », vous devez :", choices: ["Garantir un chiffre énorme", "Expliquer qu'il n'y a pas de garantie, mais un potentiel réel", "Mentir pour le convaincre", "Refuser de répondre"], answer: 1 },
  { q: "Le meilleur argument pour une petite boutique est :", choices: ["Plus de visibilité et nouveaux clients", "Plus de charges", "Moins de ventes", "Plus de complications"], answer: 0 },
  { q: "Si vous deviez trouver 10 vendeurs en 7 jours, la meilleure méthode est :", choices: ["Attendre qu'ils viennent", "Faire une liste, appeler, visiter, relancer", "Poster une seule fois et attendre", "Demander à un ami uniquement"], answer: 1, antiFraud: true },
  { q: "La persévérance signifie :", choices: ["Continuer intelligemment malgré les refus", "Harceler", "Abandonner vite", "Ne jamais écouter"], answer: 0 },
  { q: "Un vendeur sans photos produits doit être :", choices: ["Rejeté automatiquement", "Aidé à démarrer correctement", "Ignoré", "Critiqué"], answer: 1 },
  { q: "Un bon ambassadeur vend d'abord :", choices: ["Une promesse irréaliste", "Une opportunité claire", "Une illusion", "Un contrat compliqué"], answer: 1 },
  { q: "Quel vendeur est le plus prometteur ?", choices: ["Artisan avec produit unique et motivation", "Vendeur sans produit", "Commerçant qui refuse toute information", "Personne sans activité"], answer: 0, antiFraud: true },
  { q: "Un vendeur hésite à rejoindre la plateforme. Vous devez :", choices: ["Identifier sa peur principale", "Couper la conversation", "Dire qu'il a tort", "Le menacer de perdre l'occasion"], answer: 0 },
  { q: "Le digital permet surtout à un commerçant traditionnel de :", choices: ["Toucher plus de clients", "Fermer son magasin", "Augmenter ses problèmes", "Perdre son identité"], answer: 0 },
  { q: "L'ambassadeur idéal est :", choices: ["Autonome", "Toujours en attente d'ordres", "Passif", "Désorganisé"], answer: 0 },
  { q: "Dans un marché populaire, votre première action serait :", choices: ["Observer les vendeurs actifs et engager la discussion", "Acheter sans parler", "Partir après 2 minutes", "Chercher uniquement les grandes marques"], answer: 0, antiFraud: true },
  { q: "Une bonne prospection commence par :", choices: ["Une cible claire", "Une improvisation totale", "Une promesse de richesse", "Un discours très long"], answer: 0 },
  { q: "Le meilleur message à un vendeur Facebook est :", choices: ["« Bonjour, vos produits peuvent intéresser plus de clients via notre marketplace. »", "« Donnez-moi votre argent. »", "« Vous devez vendre chez nous. »", "« Je ne sais pas pourquoi je vous écris. »"], answer: 0 },
  { q: "Si un vendeur demande les conditions, vous devez :", choices: ["Être clair et transparent", "Éviter la question", "Répondre vaguement", "Inventer"], answer: 0 },
  { q: "Le risque principal d'un ambassadeur non sérieux est :", choices: ["Perdre la confiance des vendeurs", "Gagner trop vite", "Être trop organisé", "Mieux suivre les recrues"], answer: 0 },
  { q: "Un vendeur vend des pièces auto rares. Est-ce intéressant ?", choices: ["Oui, si le produit est légal et vendable", "Non, uniquement vêtements", "Non, uniquement alimentaire", "Impossible à savoir"], answer: 0, antiFraud: true },
  { q: "Une bonne relation commerciale repose sur :", choices: ["Confiance", "Pression", "Mensonge", "Silence"], answer: 0 },
  { q: "Le meilleur indicateur de réussite d'un ambassadeur est :", choices: ["Nombre de vendeurs actifs qui vendent", "Nombre de promesses", "Nombre de discussions sans suite", "Nombre de diplômes"], answer: 0 },
  { q: "Si un vendeur ne répond plus, il faut :", choices: ["Relancer poliment", "L'insulter", "Abandonner définitivement immédiatement", "Le bloquer"], answer: 0 },
  { q: "La marketplace aide surtout le vendeur à :", choices: ["Accéder à plus de clients", "Réduire la qualité", "Vendre moins", "Se cacher"], answer: 0 },
  { q: "Quel exemple correspond le mieux à « tout peut se vendre » ?", choices: ["Artisanat, stock importé, matériel professionnel", "Seulement stylos", "Seulement téléphones", "Seulement vêtements"], answer: 0, antiFraud: true },
  { q: "Un ambassadeur efficace travaille avec :", choices: ["Méthode", "Désordre", "Attente", "Chance uniquement"], answer: 0 },
  { q: "Le meilleur comportement en entretien visio est :", choices: ["Donner des exemples concrets", "Réciter des phrases générales", "Lire un texte préparé sans naturel", "Répondre hors sujet"], answer: 0 },
  { q: "Un candidat qui répond trop parfaitement à tout peut être :", choices: ["À vérifier en entretien", "Automatiquement excellent", "Automatiquement rejeté", "Sans intérêt"], answer: 0 },
  { q: "Si on vous demande « où prospecter demain matin ? », meilleure réponse :", choices: ["Zone commerciale proche + 10 boutiques ciblées", "Internet seulement sans action", "Je verrai plus tard", "N'importe où sans plan"], answer: 0, antiFraud: true },
  { q: "Une objection est :", choices: ["Une occasion de mieux comprendre", "Une attaque personnelle", "Une fin définitive", "Une preuve d'échec"], answer: 0 },
  { q: "Le suivi des recrues est important car :", choices: ["Le revenu dépend aussi de leur activité", "Il ne sert à rien", "Il remplace les ventes", "Il ralentit tout"], answer: 0 },
  { q: "Le meilleur vendeur à éviter est :", choices: ["Celui qui veut vendre des produits douteux", "Celui qui a de bons produits", "Celui qui veut apprendre", "Celui qui a besoin de visibilité"], answer: 0 },
  { q: "Le Made in Tunisia est important car :", choices: ["Il peut valoriser des produits locaux", "Il n'a aucune valeur", "Il doit rester invisible", "Il ne concerne pas la marketplace"], answer: 0 },
  { q: "Une bonne phrase d'approche terrain est :", choices: ["« Bonjour, je travaille sur une solution pour aider les vendeurs à gagner plus de visibilité. »", "« Je viens perdre votre temps. »", "« Je ne connais pas votre activité. »", "« Signez sans lire. »"], answer: 0, antiFraud: true },
  { q: "Le candidat idéal doit accepter que :", choices: ["Les résultats demandent de l'action", "L'argent arrive sans effort", "Le diplôme suffit", "Le hasard fait tout"], answer: 0 },
  { q: "Un bon ambassadeur doit savoir :", choices: ["Écouter", "Interrompre", "Ignorer", "Juger"], answer: 0 },
  { q: "Le meilleur usage des réseaux sociaux est :", choices: ["Identifier des vendeurs actifs", "Se distraire uniquement", "Copier-coller au hasard", "Critiquer les concurrents"], answer: 0 },
  { q: "Une bonne fiche vendeur doit contenir :", choices: ["Nom, activité, contact, produits, potentiel", "Seulement prénom", "Seulement ville", "Rien"], answer: 0 },
  { q: "Si vous contactez 30 vendeurs et 5 répondent, vous devez :", choices: ["Continuer, relancer, améliorer votre approche", "Abandonner", "Dire que le projet ne marche pas", "Attendre un mois"], answer: 0, antiFraud: true },
  { q: "Un ambassadeur performant transforme :", choices: ["Les contacts en vendeurs actifs", "Les idées en excuses", "Les refus en abandon", "Les messages en silence"], answer: 0 },
  { q: "La meilleure motivation pour ce poste est :", choices: ["Gagner plus en créant des opportunités", "Ne rien faire", "Avoir un titre seulement", "Éviter tout contact"], answer: 0 },
  { q: "Un vendeur professionnel apprécie surtout :", choices: ["La clarté", "Le flou", "La pression", "Les promesses irréalistes"], answer: 0 },
  { q: "Si vous deviez choisir une seule action aujourd'hui :", choices: ["Faire une liste de 20 vendeurs potentiels", "Attendre les instructions", "Lire uniquement l'annonce", "Regarder les autres travailler"], answer: 0, antiFraud: true },
  { q: "L'évolution vers responsable secteur dépend surtout :", choices: ["Des résultats terrain", "De l'âge", "Du hasard", "Du nombre de likes"], answer: 0 },
  { q: "Une rémunération variable signifie :", choices: ["Elle dépend des résultats", "Elle est toujours fixe", "Elle est impossible", "Elle est automatique"], answer: 0 },
  { q: "Le meilleur candidat n'est pas forcément celui qui :", choices: ["A le plus beau CV", "Est sérieux", "Est motivé", "Passe à l'action"], answer: 0 },
  { q: "Quel signe montre un candidat terrain ?", choices: ["Il donne des lieux précis de prospection", "Il parle uniquement de théorie", "Il évite les exemples", "Il répond avec des phrases vagues"], answer: 0, antiFraud: true },
  { q: "Un bon ambassadeur doit être capable de :", choices: ["Créer un premier contact", "Éviter les gens", "Refuser d'appeler", "Ne jamais relancer"], answer: 0 },
  { q: "Une bonne prospection doit être :", choices: ["Régulière", "Accidentelle", "Rare", "Sans suivi"], answer: 0 },
  { q: "Le meilleur état d'esprit est :", choices: ["« Je peux apprendre et progresser »", "« Je veux gagner sans agir »", "« Je refuse les refus »", "« Je ne contacte personne »"], answer: 0 },
  { q: "Si un vendeur demande « pourquoi vous ? », vous devez répondre avec :", choices: ["Bénéfices concrets", "Colère", "Silence", "Mépris"], answer: 0 },
  { q: "Un candidat qui utilise l'IA risque surtout de :", choices: ["Donner des réponses trop générales sans exemples locaux", "Répondre plus humainement", "Avoir plus d'expérience terrain", "Connaître automatiquement les commerçants"], answer: 0, antiFraud: true },
  { q: "L'ambassadeur doit éviter :", choices: ["Les fausses promesses", "La transparence", "Le suivi", "L'écoute"], answer: 0 },
  { q: "Un vendeur recruté mais inactif est :", choices: ["À relancer et accompagner", "Une réussite complète", "À ignorer définitivement", "Un problème impossible"], answer: 0 },
  { q: "Le plus important au début est de :", choices: ["Créer des premiers contacts qualifiés", "Attendre un salaire fixe", "Tout déléguer", "Ne rien tester"], answer: 0 },
  { q: "Si vous habitez à Sousse, exemple concret de prospection :", choices: ["Médina, boutiques, artisans, zones commerciales", "Uniquement aéroport", "Uniquement plage", "Uniquement administrations"], answer: 0, antiFraud: true },
  { q: "La phrase « pas de limite de revenus » veut dire :", choices: ["Les revenus peuvent évoluer selon les résultats", "Argent garanti sans effort", "Salaire fixe énorme", "Paiement sans vendeur"], answer: 0 },
  { q: "Un bon ambassadeur respecte :", choices: ["Le vendeur et son temps", "Seulement ses intérêts", "Aucun engagement moral", "Personne"], answer: 0 },
  { q: "Le meilleur moyen d'apprendre vite est :", choices: ["Tester, mesurer, corriger", "Attendre", "Se plaindre", "Copier sans comprendre"], answer: 0 },
  { q: "Quelle réponse paraît trop IA et faible ?", choices: ["« Je vais optimiser la synergie commerciale omnicanale. »", "« Je vais visiter 15 boutiques cette semaine. »", "« Je vais contacter des artisans locaux. »", "« Je vais relancer les vendeurs intéressés. »"], answer: 0, antiFraud: true },
  { q: "Une bonne opportunité commerciale doit être :", choices: ["Compréhensible pour le vendeur", "Floue", "Complexe volontairement", "Cachée"], answer: 0 },
  { q: "Le vendeur idéal pour démarrer est :", choices: ["Accessible, motivé, avec produits disponibles", "Introuvable", "Sans contact", "Sans produit"], answer: 0 },
  { q: "Le suivi sert à :", choices: ["Transformer l'inscription en ventes", "Remplacer la prospection", "Faire semblant", "Éviter le vendeur"], answer: 0 },
  { q: "Si vous deviez répondre en entretien, le meilleur exemple est :", choices: ["« Je peux commencer par les boutiques de mon quartier et les vendeurs Facebook que je repère. »", "« Je vais développer une stratégie internationale abstraite. »", "« Je vais attendre la formation. »", "« Je n'ai aucune idée. »"], answer: 0, antiFraud: true },
  { q: "Un ambassadeur doit accepter :", choices: ["Le rejet", "L'inaction", "Le flou total", "L'absence de suivi"], answer: 0 },
  { q: "Un bon vendeur marketplace doit avoir :", choices: ["Produit vendable + volonté de vendre", "Seulement promesses", "Aucun stock", "Aucune disponibilité"], answer: 0 },
  { q: "La meilleure relance est :", choices: ["Courte, polie, utile", "Longue et agressive", "Confuse", "Manipulatrice"], answer: 0 },
  { q: "Le candidat réellement motivé parle souvent de :", choices: ["Plan d'action concret", "Concepts vagues", "Phrases copiées", "Excuses"], answer: 0, antiFraud: true },
  { q: "L'activité est compatible avec les études car :", choices: ["Elle est flexible", "Elle impose un bureau fixe", "Elle demande 12h par jour obligatoires", "Elle interdit les étudiants"], answer: 0 },
  { q: "Un bon objectif de première semaine est :", choices: ["Identifier 30 prospects et obtenir 5 rendez-vous", "Attendre", "Demander un poste fixe immédiatement", "Ne contacter personne"], answer: 0 },
  { q: "La confiance se gagne par :", choices: ["Honnêteté et suivi", "Mensonge", "Pression", "Silence"], answer: 0 },
  { q: "Un candidat qui répond en 3 secondes à toutes les questions complexes peut être :", choices: ["À vérifier", "Automatiquement parfait", "Forcément meilleur", "Sans risque"], answer: 0, antiFraud: true },
  { q: "Un ambassadeur doit comprendre que :", choices: ["La qualité des vendeurs compte plus que le nombre brut", "Il faut recruter n'importe qui", "Le suivi ne sert à rien", "Les mauvais produits suffisent"], answer: 0 },
  { q: "La meilleure attitude face à un vendeur lent est :", choices: ["Relancer avec patience et clarté", "S'énerver", "L'abandonner immédiatement", "Le ridiculiser"], answer: 0 },
  { q: "Le poste récompense surtout :", choices: ["L'action", "L'attente", "Le silence", "La chance seule"], answer: 0 },
  { q: "Quel exemple est le plus terrain ?", choices: ["« Je vais faire une tournée des rues commerciales et noter les contacts. »", "« Je vais créer une vision disruptive. »", "« Je vais optimiser la scalabilité relationnelle. »", "« Je vais réfléchir longtemps. »"], answer: 0, antiFraud: true },
  { q: "Pour convaincre un importateur avec stock, l'argument clé est :", choices: ["Nouveau canal pour écouler le stock", "Moins de clients", "Plus de stockage", "Moins de visibilité"], answer: 0 },
  { q: "Le bon ambassadeur sait que le revenu :", choices: ["Se construit", "Tombe automatiquement", "Est garanti sans travail", "Ne dépend de rien"], answer: 0 },
  { q: "La meilleure qualité commerciale est :", choices: ["Régularité", "Impulsivité", "Abandon", "Isolement"], answer: 0 },
  { q: "Si vous deviez citer 3 cibles immédiates :", choices: ["Artisans, boutiques, vendeurs Facebook", "Satellites, ministères, hôpitaux", "Banques centrales, ambassades, universités uniquement", "Aucune cible"], answer: 0, antiFraud: true },
  { q: "Un vendeur qui réussit sur la plateforme permet à l'ambassadeur de :", choices: ["Gagner davantage", "Perdre sa commission", "Arrêter toute activité", "Être remplacé automatiquement"], answer: 0 },
  { q: "Le meilleur comportement avec l'équipe marketplace est :", choices: ["Remonter les informations terrain", "Cacher les problèmes", "Inventer des résultats", "Ne jamais communiquer"], answer: 0 },
  { q: "Si un candidat utilise des phrases très longues et sans exemple, cela peut indiquer :", choices: ["Réponse assistée ou peu authentique", "Grande expérience terrain certaine", "Meilleur profil automatiquement", "Aucun risque"], answer: 0, antiFraud: true },
  { q: "Le meilleur vendeur à prioriser est :", choices: ["Celui qui peut mettre rapidement des produits en ligne", "Celui qui refuse tout", "Celui qui n'a rien à vendre", "Celui qui ne répond jamais"], answer: 0 },
  { q: "Un bon ambassadeur doit être capable de :", choices: ["Transformer une conversation en opportunité", "Éviter les conversations", "Attendre un miracle", "Travailler sans objectif"], answer: 0 },
  { q: "Une réponse authentique contient souvent :", choices: ["Exemple personnel ou local", "Formule générale parfaite", "Aucun détail", "Langage très robotique"], answer: 0, antiFraud: true },
  { q: "Pour réussir, il faut surtout :", choices: ["Prospecter, relancer, suivre", "Attendre, espérer, oublier", "Critiquer, comparer, abandonner", "Copier, coller, disparaître"], answer: 0 },
  { q: "Le candidat idéal comprend que cette opportunité est :", choices: ["Flexible mais exige des résultats", "Facile sans action", "Un salaire garanti immédiatement", "Sans aucun effort"], answer: 0 },
  { q: "La meilleure phrase finale en entretien serait :", choices: ["« Je peux commencer cette semaine avec une liste de prospects dans ma région. »", "« Je vais voir plus tard. »", "« Je veux gagner sans prospecter. »", "« Je n'aime pas parler aux gens. »"], answer: 0, antiFraud: true }
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
export const DURATION_PER_QUESTION_SEC = 30;
